name: Python - Test

on:
  push:
    paths:
      - '.github/workflows/python-test.yml'
      - 'python/**'
  pull_request:
    paths:
      - '.github/workflows/python-test.yml'
      - 'python/**'

jobs:
  run-python-tests:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo add-apt-repository ppa:wireshark-dev/stable
          sudo apt update
          sudo apt upgrade -y
          sudo apt -y install \
            tshark \
            python3-pytest

      - name: Run tests
        run: pytest
        working-directory: python/test
